login:
  port: 1237
  threads: 10
auth:
  otp: false
  otp_max_try: 3
  ars: false          # Not release by XLGames in leaked client
  pc_cert: false      # Not release by XLGames in leaked client
  pc_cert_max_try: 3